SELECT DISTINCT Name 
FROM sys.procedures
WHERE OBJECT_DEFINITION(OBJECT_ID) LIKE '%Trans_Raw%'
AND OBJECT_DEFINITION(OBJECT_ID) LIKE '%Cust_ID%'
AND OBJECT_DEFINITION(OBJECT_ID) LIKE '%Vendors_Raw%'
AND OBJECT_DEFINITION(OBJECT_ID) LIKE '%Cust_ID%';